### ISSUE TITLE
Alert escalation paths

### ISSUE THREAD

**Issue by The-smooth-operator** [mozilla-iam/iam-infra#26]
I want to share my thoughts with you regarding escalation paths, and if possible get some feedback. 
My idea is to have 3 different kind of alerts:
 - alert_developer_{warning, critical}: alerts regarding apps misbehaving. Ex: Pods of a particular service are restarting in loop. Escalation path: Slack #iam o #iam-bots. Can be split b severity to a email to the devs of that application.
 - alert_system_{warning, critical}: alerts regarding infrastructure, Ex: new pods can't be scheduled. Escalation path: email and/or slack to the team in charge of the cluster (your team?)
 - alert_external: this will be done from New Relic and try to measure the user experience. Ex: Browser tries loading SSO dashboard, login in, clicking a link and verifying it got correctly redirected. Escalation path: MOC via PagerDuty.

The idea behind this is that MOC will be first level of support when users are experiencing problems (we will need a k8s account for MOC team members with only Read access to make first level troubleshooting, and runbooks written). If there's a real problem we will escalate to the Service Owner who can debug faster looking at slack or email for low level alertsl. For example after being alerted by a MOC team member because SSO is down, she can check slack to see if there are other alerts internal to that app.

What do you think?

**Comment by danielhartnell** [comment]
This seems like a reasonable approach to me. Some of my colleagues have setup Prometheus in the past and I believe they accomplished something somewhat similar by setting up routes in AlertManager structured like this:

```
  - receiver: platform-critical
  - receiver: platform-non-critical
  - receiver: application-critical
  - receiver: application-non-critical
```

I'm only sharing the naming because it looks like they felt a similar approach was the best way to structure the alert routes (I like your introduction of `alert_external`).

The actual escalation paths look like a great start to me as well. I'm comfortable providing restricted access for the MOC to access our cluster for now (it seems like the simplest solution). In the future, it might be interesting to have the MOC scrape metrics from our Prometheus service and generate alerts on that side (just to centralize monitoring and alerting) but that can be a discussion for another time. I don't want to complicate things.

**Comment by The-smooth-operator** [comment]
This issue is almost one-year-old and somehow not relevant anymore.
All the alerts we have been adding have been labeled with teams and priorities, however the only escalation path now available is to a Slack channel.

The reason why this has not been moving forward is because until now we don't have the need to route alerts to different services, like can be PagerDuty or email. To be honest we don't have many alerts popping up.
If this need comes in the future, we will be definitely implementing it. However doesn't make sense to keep the ticket open until the necessity arrives, but the other way around: open an issue when we need this changes.
